export const props = [
  {
    title: 'className',
    description: 'Classes for custom styling',
    type: 'string',
    required: false,
    defaultValue: '""',
  },
  {
    title: 'description',
    description: 'A description of what the component provides',
    type: 'string',
    required: false,
    defaultValue: '""',
  },
  {
    title: 'mainText',
    description: 'A more in depth explanation of the component',
    type: 'string',
    required: false,
    defaultValue: '""',
  },
  {
    title: 'onContentLoad',
    description: 'Callback function to be called when the content has initially loaded',
    type: '() => void',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'codeExamples',
    description: 'Data used to render code examples of component usages',
    type: 'IComponentUsage[]',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'customContent',
    description: 'Inejction of custom content onto the documentation page',
    type: 'JSX.Element',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'props',
    description: 'Data used to render list of component props',
    type: 'IPropertyDetail[]',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'styles',
    description: 'Data used to render a table of classNames used to style the component',
    type: 'IStyleDetail',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'outro',
    description: 'Description in the bottom of the documentation page',
    type: 'JSX.Element',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'preNav',
    description: 'Data used to render navigation element in the documentation page footer',
    type: 'IFooterNav',
    required: false,
    defaultValue: 'none',
  },
  {
    title: 'nextNav',
    description: 'Data used to render navigation element in the documentation page footer',
    type: 'IFooterNav',
    required: false,
    defaultValue: 'none',
  },
];
